#ifndef CARTESMSLCONFIG_HPP
#define CARTESMSLCONFIG_HPP

#include "MySmileLife.hpp"

namespace MySmileLife{

    struct ProprietesCarte{
                int id;
                string nom;
                int nbSmile;
                CarteType cType;
                CarteSousType csType;
                int nbCarte;
        };
    const vector<ProprietesCarte> vecMSLCarte = {
        { 0,"Architecte", 2, carteMetier, csArchitecte,1},
        { 1,"Astronaute", 2, carteMetier, csAstronaute,1},
        { 2,"Avocat", 2, carteMetier, csAvocat,1},
        { 3,"Bandit", 2, carteMetier, csBandit,1},
        { 4,"Barman", 2, carteMetier, csBarman,1},
        { 5,"ChefDesAchats", 2, carteMetier, csChefDesAchats,1},
        { 6,"ChefDesVentes", 2, carteMetier, csChefDesVentes,1},
        { 7,"Chercheur", 2, carteMetier, csChercheur,1},
        { 8,"Chirurgien", 2, carteMetier, csChirurgien,1},
        { 9,"Designer", 2, carteMetier, csDesigner,1},
        {10,"Ecrivain", 2, carteMetier, csEcrivain,1},
        {11,"Garagiste", 2, carteMetier, csGaragiste,1},
        {12,"GrandProf", 2, carteMetier, csGrandProf,1},
        {13,"Gourou", 2, carteMetier, csGourou,1},
        {14,"Jardinier", 2, carteMetier, csJardinier,1},
        {15,"Journaliste", 2, carteMetier, csJournaliste,1},
        {16,"Medecin", 2, carteMetier, csMedecin,1},
        {17,"Medium", 2, carteMetier, csMedium,1},
        {18,"Militaire", 2, carteMetier, csMilitaire,1},
        {19,"Pharmacien", 2, carteMetier, csPharmacien,1},
        {20,"PiloteDeLigne", 2, carteMetier, csPiloteDeLigne,1},
        {21,"Pizzaiolo", 2, carteMetier, csPizzaiolo,1},
        {22,"Plombier", 2, carteMetier, csPlombier,1},
        {23,"Policier", 2, carteMetier, csPolicier,1},
        {24,"ProfDeFrancais", 2, carteMetier, csProf,1},
        {25,"ProfDeMaths", 2, carteMetier, csProf,1},
        {26,"ProfDHistoire", 2, carteMetier, csProf,1},
        {27,"ProfDAnglais", 2, carteMetier, csProf,1},
        {28,"Serveur", 2, carteMetier, csServeur,1},
        {29,"Stripteaser", 2, carteMetier, csStripteaser,1},
        {30,"Etude Simple", 1, carteEtude, csEtudeSimple,22},
        {31,"Etude Double", 1, carteEtude, csEtudeDouble,3},
        {32,"Salaire 1", 1, carteSalaire, csSalaire1,10},
        {33,"Salaire 2", 1, carteSalaire, csSalaire2,10},
        {34,"Salaire 3", 1, carteSalaire, csSalaire3,10},
        {35,"Salaire 4", 1, carteSalaire, csSalaire4,10},
        {36,"Anniversaire", 0, carteSpecial, csAnniversaire,1},
        {37,"ArcEnCiel", 0, carteSpecial, csArcEnCiel,1},
        {39,"cCasino", 0, carteSpecial, csCasino,1},
        {40,"Chance", 0, carteSpecial, csChance,1},
        {41,"EtoileFilante", 0, carteSpecial, csEtoileFilante,1},
        {42,"Heritage", 0, carteSpecial, csHeritage,1},
        {43,"Piston", 0, carteSpecial, csPiston,1},
        {43,"Troc", 0, carteSpecial, csTroc,1},
        {44,"Tsunami", 0, carteSpecial, csTsunami,1},
        {45,"Vengeance", 0, carteSpecial, csVengeance,1},
        {46,"Adultere", 0, carteSpecial, csAdultere,3},
        {47,"LegionHonneur", 3, carteSpecial, csLegionHonneur,1},
        {48,"GrandPrixExcellence", 4, carteSpecial, csGrandPrixExcellence,2},
        {49,"Leia", 2, carteEnfant, csFille,1},
        {50,"Hermione", 2, carteEnfant, csFille,1},
        {51,"Lara", 2, carteEnfant, csFille,1},
        {52,"Diana", 2, carteEnfant, csFille,1},
        {53,"Zelda", 2, carteEnfant, csFille,1},
        {54,"Luke", 2, carteEnfant, csGarcon,1},
        {55,"Mario", 2, carteEnfant, csGarcon,1},
        {56,"Luigi", 2, carteEnfant, csGarcon,1},
        {57,"Harry", 2, carteEnfant, csGarcon,1},
        {58,"Rocky", 2, carteEnfant, csGarcon,1},
        {59,"Flirt", 1, carteFlirt, csAuParc,2},
        {60,"Flirt", 1, carteFlirt, csAuBar,2},
        {61,"Flirt", 1, carteFlirt, csAuTheatre,2},
        {62,"Flirt", 1, carteFlirt, csAuCinema,2},
        {63,"Flirt", 1, carteFlirt, csEnBoiteDeNuit,2},
        {64,"Flirt", 1, carteFlirt, csAuRestaurant,2},
        {65,"Flirt", 1, carteFlirt, csAuZoo,2},
        {66,"Flirt", 1, carteFlirt, csSurInternet,2},
        {67,"Flirt", 1, carteFlirt, csAuCamping,2},
        {68,"Flirt", 1, carteFlirt, csALHotel,2},     
        {69,"Mariage", 3, carteMariage, csAucun,7},
        {70,"Accidents", 0, carteMalus, csAccidents,1},
        {71,"Burne Out", 0, carteMalus, csBurnOut,1},
        {72,"Dit Vorce", 0, carteMalus, csDivorce,1},
        {73,"Un pot", 0, carteMalus, csImpotsRevenus,1},
        {74,"Lit 100 ciments", 0, carteMalus, csLicenciement,1},
        {75,"Mâle à dit", 0, carteMalus, csMaladie,1},
        {76,"Redoublement", 0, carteMalus, csRedoublement,1},
        {77,"Prison", 0, carteMalus, csPrison,1},
        {78,"Attentat", 0, carteMalus, csAttentat,1},
        {79,"Chat", 1, carteAnimal, csAucun,1},
        {80,"chien", 1, carteAnimal, csAucun,1},
        {81,"Lapin", 1, carteAnimal, csAucun,1},
        {82,"Oiseau", 1, carteAnimal, csAucun,1},
        {83,"Licorne", 3, carteAnimal, csLicorne,1},
        {84,"Londres", 1, carteVoyage, csAucun,1},
        {85,"New York", 1, carteVoyage, csAucun,1},
        {86,"Rio de Janeiro", 1, carteVoyage, csAucun,1},
        {87,"Sydney", 1, carteVoyage, csAucun,1},
        {88,"Le Caire", 1, carteVoyage, csAucun,1},
        {89,"Maison 6", 1, carteMaison, csMaison6,2},
        {90,"Maison 8", 2, carteMaison, csMaison8,2},
        {91,"Maison 10", 3, carteMaison, csMaison10,1}
    };
}
#endif